version: '3'

services:
  api-gateway:
    container_name: api-gateway-service-container
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user
      - product

  product:
    container_name: product-service-container
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-coju2f8cmk4c73c40l60-a.oregon-postgres.render.com/ecommerce_vlw8
      SPRING_DATASOURCE_USERNAME: batman
      SPRING_DATASOURCE_PASSWORD: kclJanmxhFfyx0o5bEgix6OhwGReGTPy
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  user:
    container_name: user-service-container
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - product

volumes:
  postgres-data: