version: '3'

services:
  api-gateway:
    restart: always
    container_name: api-gateway-service-container
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user
      - product
      - order

  user:
    container_name: user-service-container
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env

  product:
    container_name: product-service-container
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env

  order:
    container_name: order-service-container
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - user
      - product

  payment:
    container_name: payment-service-container
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      - order

  # frontend:
  #   container_name: frontend-service-container
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api-gateway

volumes:
  postgres-data: