version: '3'
services:
  postgres:
    container_name: postgresql-container
    image: postgres:latest
    environment:
      POSTGRES_HOST: dpg-coju2f8cmk4c73c40l60-a.oregon-postgres.render.com
      POSTGRES_USER: batman
      POSTGRES_PASSWORD: kclJanmxhFfyx0o5bEgix6OhwGReGTPy
      POSTGRES_DB: ecommerce_vlw8
#    volumes:
#      - D:\Ahmed\College\4th Year\2nd Term\Cloud Computing\Project\data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  product:
    container_name: product-service-container
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-coju2f8cmk4c73c40l60-a.oregon-postgres.render.com/ecommerce_vlw8
      SPRING_DATASOURCE_USERNAME: batman
      SPRING_DATASOURCE_PASSWORD: kclJanmxhFfyx0o5bEgix6OhwGReGTPy
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    restart: always

  user:
    container_name: user-service-container
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - product
    restart: always
volumes:
  postgres-data: