server:
  port: 8080

spring:
  #  main:
  #    web-application-type: reactive

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

      routes:
        - id: user
          uri: http://user:8081
          predicates:
            - Path=/api/users/**

        - id: product
          uri: http://product:8082
          predicates:
            - Path=/api/products/**

        - id: order
          uri: http://order:8083
          predicates:
            - Path=/api/orders/**
